### ISSUE TITLE
Cannot detect Zooey character after summoning Death

### ISSUE THREAD

**Issue by giauten** [Masuzu/ZooeyBot#1010]
After i summoning Death to bring Zooey into the battle, the command right after it has been skipped and it wont detect Zooey character as follow

![image](https://user-images.githubusercontent.com/43314003/51421396-4ff34000-1bd0-11e9-97aa-91299d85d0d7.png)

**Comment by Masuzu** [comment]
Hello,
Let me check this and follow up. It looks like a bug indeed.

**Comment by Masuzu** [comment]
This should now be fixed in v3.5.1 Thank you for reporting this issue.

**Comment by giauten** [comment]
Hi, this issue still occurs in v3.5.1
Note that I set UseViramate=false becuz of the of the "cannot use 1st skill" bug

**Comment by moourns** [comment]
I also have the same issue. I'm using UseViramate=true but without highlighting the character portraits. I put in a Refresh() before using Zooey's skills to see if that would solve the issue but I get the same error that the OP has mentioned originally.

**Comment by giauten** [comment]
@Masuzu sr i dunno how to reopen
