### ISSUE TITLE
Bot gets stuck on popup after side scrolling stage

### ISSUE THREAD

**Issue by soufflenote** [Masuzu/ZooeyBot#287]
Hi! First off, thank you for all your hard work, I'm delighted with the program so far! I was having issues however when I try to run any quest with a side scrolling stage. The bot will run fine for the first five to ten minutes, sometimes a bit longer, then get stuck on the side scrolling popup and is seemingly unable to find the "OK" button to dismiss it. If I manually push the okay button, Zooey reengages and continues with the battle on her own. I'm curious as to why this is happening? 

I'm including two screenshots below, of the bot setup right before clicking on the quest and after it gets stuck. I've double checked the settings, and also reset the .ini configuration file to the default, clean downloaded one in case an option I had set or my battle scripts had broken something, to no result. The issue persisted from version 1.19.3 to 1.20.0 as well. 

Any ideas on what could be causing it, or what I should try to do to fix it? Thank you, and take care!
![bug1](https://user-images.githubusercontent.com/32054761/30531021-67c92eca-9c19-11e7-9060-2b0df0a23594.png)
![bug2](https://user-images.githubusercontent.com/32054761/30531020-67c76b1c-9c19-11e7-8126-8483d9f4077f.png)

**Comment by Masuzu** [comment]
Hi,

Please make sure to select the Network tab in the DevTools window. You may experience slowdowns after a while otherwise.

**Comment by soufflenote** [comment]
Thank you for your reply! I tried using the network tab and I still encounter the same bug. To comment on something you said, she does seem to be infinitely looping and trying to close the popup constantly, but she can't seem to find the OK button when she gets stuck. It doesn't happen every time; I tried timing it to see if it was regular, and so far it's taken anywhere from seven minutes to a full half hour before the bug triggers. Once it does, though, Zooey gets stuck on a very small section on the lower right of the screen trying to click on the OK button.

Please let me know if there's any more information I can help with! I'd be happy to provide additional details or try to run any tests you might consider helpful. Take care!

**Comment by Masuzu** [comment]
Thank you for the valuable feedback.
Ah, I get it now: depending on how fast your computer loads the page, the OK button position might be incorrectly detected, resuling in Zooey trying to click repeatedly on a "fictive" OK button at a wrong location. I never encountered this bug but my computer specs made this test really biased.
I will do something about it within 24 hours.

It is unrelated but please make sure to set the parameter `ChromeDevToolsWindowDockedOnTheRight` to `true` if not done already, as your Chrome Devtools window is docked on the right (depending on what you usually use/your liking).

**Comment by Masuzu** [comment]
This should be addressed in version 1.21.0
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-21-0

I'll leave this issue open for another few days in case it does not.

**Comment by Nanaya8** [comment]
I had the same issue, version 1.21.0 doesn't seem to fix it. Bot gets stuck about 30% of the time.
I did what you asked and tried to move the cursor:
https://i.imgur.com/3vnejqp.jpg
This is the area where it moves back (the screenshot didn't actually catch the cursor itself, sorry).
That would be the same area where the cursor is placed when pressing "ok" in the summon selection screen. 
I'm also having a similar issue, sometimes the bot will get stuck in the result page. I can "unstuck" it by using viramate's repeat quest fuction.

**Comment by Masuzu** [comment]
I never ever have this issue on my side (tested on 2 computers both having an Intel i7 processor).
Does it say "Dismissing the stage popup" in the console window when you faced the situation reported in the enclosed picture?
I'd like to know the console messages displayed in the console when it gets stuck too please.

**Comment by Nanaya8** [comment]
Yeah it says that. It looks like he's still trying to click the "ok" button of the summon selection screen. As for the second problem, I'm having it for gw farming too. It just stops in the result page. It doesn't happen all the time though. Maybe a ping related problem? https://i.imgur.com/vqgHs3T.jpg

**Comment by Masuzu** [comment]
Oh that thing again about the result page. Zooey should try to navigate again to the summon page since the last patch if this happens, after `MaxTriggerDelayInMsBeforeFallback` milliseconds, so I am quite puzzled it still happens.
Unfortunately yes it's a ping issue. But even from EU there is not such issue unless your connection is really bad.

**Comment by Masuzu** [comment]
Mitigation provided in last release:
- for the summon selection page, Zooey will navigate again to the summon selection page after failing for MaxTriggerDelayInMsBeforeFallback milliseconds.
- same thing for the side scroll stage.
