### ISSUE TITLE
Scheduling: When summon not found and goes to trial mode the repeat count gets incremented

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#291]
I noticed when trying to run Celeste showdonw 3 times
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300251/1", 15, 3) 

But one time the preferred summon is not found so it goes to trial mode. And it stopped only after 2 runs I think it counted the trial run as 1 run

**Comment by Masuzu** [comment]
Thank you for reporting this bug.

**Comment by Masuzu** [comment]
This should be fixed in version 1.21.0
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-21-0

**Comment by breinjhel** [comment]
I can still reproduce this on 1.21.0 skipping counter due to trial battle
