### ISSUE TITLE
is there a way to farm rise of the beasts?

### ISSUE THREAD

**Issue by MonaSaySleep** [Masuzu/ZooeyBot#30]
is there a way to farm rise of the beasts in basic mode or event? I put the raid link in the ini but no go

thanks!

**Comment by nobody0014** [comment]
damn i wish we could do this too since rise of the beasts give decent amount of gems.... but this is probably going to take awhile or not implemented at all since raids are still not supported

**Comment by Masuzu** [comment]
Yes you can already farm any quest by using the EventMode:
Simply set `EventRaidUrl` to the URL of the page of the quest you want to repeat, whether it be GW EX+ or four best or anything else.

**Comment by mdanishu** [comment]
I did this, but at the end of the first battle it says 

"zooey bot move to results page" and then doesn't do anything. Do you know what is the problem here and how to fix it?

**Comment by Masuzu** [comment]
@mdanishu This is a known limitation for now:
https://github.com/Masuzu/ZooeyBot/issues/33

**Comment by Masuzu** [comment]
Fixed version 1.3.0 which adds a new configuration parameter EventPageUrl.
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes
Set it to http://game.granbluefantasy.jp/#event/advent015 for the Rise of the Beasts event.

**Comment by itsleesuh** [comment]
Even with the address added, I am still getting redirected to the home page.

**Comment by Masuzu** [comment]
Added some wait time after the event page is loaded with version 1.3.1.

**Comment by itsleesuh** [comment]
It works fine now, but once it goes to the result page it pastes and goes to the event page and just stops there.

**Comment by Masuzu** [comment]
It should wait around 3 seconds after moving to the event page then move to the summon selection page.
Doesn't it say New page loaded: http://game.granbluefantasy.jp/#event/advent015 ?

**Comment by itsleesuh** [comment]
Yeah it says new page loaded, but then it just stays at that page. It doesn't execute the next command of going to the summoning list.

**Comment by Antialiased** [comment]
I'm also experiencing this (zooey stops after going to the event page after completing a battle)

**Comment by MonaSaySleep** [comment]
Same issue here, it starts the event fine but after 1 battle it stays on the event page.

**Comment by Masuzu** [comment]
I found out the issue. Fixed in version 1.3.2 which has just been released.

**Comment by MonaSaySleep** [comment]
its working now! did 5 battles in a row with no issues. thanks!!
