### ISSUE TITLE
can't host nightmare90 

### ISSUE THREAD

**Issue by ycalvin** [Masuzu/ZooeyBot#56]
![zooeyerror](https://cloud.githubusercontent.com/assets/21053081/26201838/cbf87eb4-3b89-11e7-8879-1e492d19171d.png)
Keep getting this error when I try to use Zooey to run GW nightmare90 boss. 
EX+ dogs work fine but nightmare90 does not. (And it is not because I don't have the meat to host) 

It seems like the error is due to not staying on the event page for long enough before attempting to enter the dungeon. 
When I enter the following URLs manually, it will let me host the run without problem. (More delay in between URLs)
http://game.granbluefantasy.jp/#event/teamraid030
http://game.granbluefantasy.jp/#event/teamraid030/supporter/718671/1

But because Zooey is so fast in entering the URLs it causes the above error.

**Comment by Masuzu** [comment]
Hi,
Thank you for reporting this issue. This is addressed in version 1.5.3: https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Comment by akira9311** [comment]
Hello, Masuzu 

Even I set the parameter to 10000ms, the problem still appears. 
It is curious, if I use my hands to do the job. No matter how fast I go, there won't be any problems.
Could you check on this issue?

**Comment by akira9311** [comment]
Hello, Masuzu

Even I set the parameter to 10000ms, the problem still appears.
It is curious, if I use my hands to do the job. No matter how fast I go, there won't be any problems.
Could you check on this issue?

**Comment by lsysz53508** [comment]
Hello, Masuzu

Even I set the parameter to 10000ms, the problem still appears.
It is curious, if I use my hands to do the job. No matter how fast I go, there won't be any problems.
Could you check on this issue?
